### ISSUE TITLE
the example in readme file donot work

### ISSUE THREAD

**Issue by HernandoR** [tarampampam/3proxy-docker#72]
curl -x http://user:passwd@publicip:8000 https://www.google.com              
curl: (7) Failed to connect to publicip port 8000 after 187 ms: Couldn't connect to server

no logs was shown
docker-compose.yaml:
```
services:
  3proxy:
    image: ghcr.io/tarampampam/3proxy:1
    container_name: 3proxy
    environment:
      PROXY_LOGIN: 'user'
      PROXY_PASSWORD: 'passwd'
      MAX_CONNECTIONS: 10000
      PROXY_PORT: 8000
      SOCKS_PORT: 8001
      PRIMARY_RESOLVER: 1.1.1.1
      SECONDARY_RESOLVER: 8.8.8.8

      #LOG_OUTPUT: /usr/local/3proxy/logs/3proxy.log
    volumes:
      - './config:/usr/local/3proxy'
    ports:
      - '8000:8000/tcp'
      - '8001:8001/tcp'
```

`/etc/3proxy/3proxy.cfg` in the container:
```
#!/bin/3proxy
config /etc/3proxy/3proxy.cfg

# you may use system to execute some external command if proxy starts
system "echo `which 3proxy`': Starting 3proxy'"

# We can configure nservers to avoid unsafe gethostbyname() usage (max 5 servers)
nserver 1.1.1.1
nserver 8.8.8.8
nserver 1.1.1.1
nserver 9.9.9.9
nserver 8.8.8.8

# nscache is good to save speed, traffic and bandwidth
nscache 65536

# Here we can change timeout values
timeouts 1 5 30 60 180 1800 15 60

# Logging docs: <https://3proxy.org/doc/howtor.html#LOGFORMAT>
log /dev/stdout
logformat "-\""+_G{""time_unix"":%t, ""proxy"":{""type:"":""%N"", ""port"":%p}, ""error"":{""code"":""%E""}, ""auth"":{""user"":""%U""}, ""client"":{""ip"":""%C"", ""port"":%c}, ""server"":{""ip"":""%R"", ""port"":%r}, ""bytes"":{""sent"":%O, ""received"":%I}, ""request"":{""hostname"":""%n""}, ""message"":""%T""}"

maxconn 10000


users user:CL:passwd
auth strong
allow user



proxy -a -p8000
socks -a -p8001

flush
```

**Comment by tarampampam** [comment]
> the example in readme file donot work

Could you show exactly where you found this example in the README file? This one:

https://github.com/tarampampam/3proxy-docker/blob/df2468d8ded9ea23db6dbb021f1d5d8c1b4e2c0a/README.md?plain=1#L105-L118

works perfectly, so I'm going to close this issue. Please describe the problem you encountered a bit more clearly so I can better understand the expected behavior, what steps you took, and what the actual result was. Thank you!

**Comment by HernandoR** [comment]
> Please describe the problem you encountered a bit more clearly so I can better understand the expected behavior

I run the container in a remote server in US. the port maping and the environments are basically same as your's.

The port seems not working, and there's no log printing out.
docker ps
```
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                                           NAMES
f84f4984b411   ghcr.io/tarampampam/3proxy:1   "/bin/mustpl -f /etc…"   2 minutes ago   Up 2 minutes   0.0.0.0:8000-8001->8000-8001/tcp, :::8000-8001->8000-8001/tcp   3proxy
f0852298aeaa   linuxserver/prowlarr:latest    "/init"                  2 weeks ago     Up 2 weeks     0.0.0.0:9696->9696/tcp, :::9696->9696/tcp                       prowlarr
```
there's no firewall set by me or the cloud provider. The 9696 port works without any effort.

cat docker-compose.yaml
```yaml
services:
  3proxy:
    image: ghcr.io/tarampampam/3proxy:1
    container_name: 3proxy
    environment:
      PROXY_LOGIN: usr
      PROXY_PASSWORD: passwd
      MAX_CONNECTIONS: 10000
      PROXY_PORT: 8000
      SOCKS_PORT: 8001
      PRIMARY_RESOLVER: 1.1.1.1
      SECONDARY_RESOLVER: 8.8.8.8
      #LOG_OUTPUT: /usr/local/3proxy/logs/3proxy.log
    volumes:
      - './config:/usr/local/3proxy'
    ports:
      - '8000:8000'
      - '8001:8001'
```

curl -x http://usr:passwd@ip:8000 https://www.google.com -v
```
*   Trying 198.23.246.123:8000...
* Connected to 198.23.246.123 (198.23.246.123) port 8000
* CONNECT tunnel: HTTP/1.1 negotiated
* allocate connect buffer
* Proxy auth using Basic with user 'lz'
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> Proxy-Authorization: Basic bHo6TGl1emhlbjA0MiM=
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Proxy-Connection: Keep-Alive
> 
* Proxy CONNECT aborted
* Closing connection
curl: (56) Proxy CONNECT aborted
```
